<template>
  <view class="page"><view v-if="loading" class="loading">正在加载医生资料…</view><view v-else-if="error" class="error-card">{{ error }}<button class="btn btn-outline btn-small" @click="load">重新加载</button></view><template v-else-if="doctor"><view class="card doctor-intro"><view class="row gap"><view class="avatar large"><image v-if="doctor.avatarUrl" :src="doctor.avatarUrl" mode="aspectFill" /><text v-else>{{ doctor.name?.slice(0, 1) }}</text></view><view><view class="doctor-name">{{ doctor.name }}</view><view class="muted top-space">{{ doctor.title || '口腔医师' }} · {{ doctor.departmentName }}</view><view class="pill top-space">门诊预约</view></view></view><view class="divider" /><view class="intro-label">擅长方向</view><view class="body">{{ doctor.specialty || '口腔常见问题诊疗' }}</view><view v-if="doctor.introduction" class="top-space"><view class="intro-label">医生简介</view><view class="body">{{ doctor.introduction }}</view></view></view><view class="section"><view class="section-title">选择就诊日期</view><view class="muted top-space">{{ dates[0]?.month }}月起 · 未来 14 天可预约时段</view><scroll-view class="date-scroll" scroll-x><view class="dates"><view v-for="day in dates" :key="day.key" :class="['date-item', { selected: selectedDate === day.key }]" @click="selectDate(day.key)"><view class="day-label">{{ day.label }}</view><view class="day-number">{{ day.day }}</view><view class="day-month">{{ day.month }}月</view></view></view></scroll-view></view><view class="section"><view class="row between"><text class="section-title">可预约时段</text><text class="link" @click="loadSchedules">刷新号源</text></view><view v-if="schedulesLoading" class="loading">正在查询号源…</view><view v-else-if="scheduleError" class="error-card top-space">{{ scheduleError }}<button class="btn btn-outline btn-small" @click="loadSchedules">重试</button></view><template v-else><view v-for="schedule in schedules" :key="schedule.id" class="card slot-card"><view><view class="slot-time">{{ timeRange(schedule) }}</view><view :class="['slot-count', { full: schedule.remainingSlots <= 0 }]">{{ schedule.remainingSlots > 0 ? `剩余 ${schedule.remainingSlots} 个号源` : '号源已约满' }}</view></view><button class="btn btn-primary btn-small" :disabled="schedule.remainingSlots <= 0" @click="book(schedule)">预约</button></view><EmptyState v-if="!schedules.length" title="当天暂无开放号源" description="可以切换其他日期，或稍后查看诊所新排班" /></template></view><view class="hint section">预约提交后需由诊所确认，请在“我的预约”查看处理结果。若需取消，请在就诊开始前按诊所规定操作。</view></template></view>
</template>
<script setup>
import { ref } from 'vue';
import { onLoad, onShow } from '@dcloudio/uni-app';
import { api } from '../../utils/request';
import { ensureLogin } from '../../utils/auth';
import { nextDates, timeRange } from '../../utils/format';
import EmptyState from '../../components/EmptyState.vue';
const doctor = ref(null); const schedules = ref([]); const loading = ref(true); const error = ref(''); const schedulesLoading = ref(false); const scheduleError = ref(''); const dates = ref(nextDates()); const selectedDate = ref(dates.value[0].key); let id = ''; let scheduleGeneration = 0; let initialized = false;
async function load() { loading.value = true; error.value = ''; try { doctor.value = await api.doctor(id); await loadSchedules(); } catch (e) { error.value = e.message; } finally { loading.value = false; } }
async function loadSchedules() { const current = ++scheduleGeneration; schedulesLoading.value = true; scheduleError.value = ''; try { const result = await api.schedules({ doctorId: id, dateFrom: selectedDate.value, dateTo: selectedDate.value }); if (current === scheduleGeneration) schedules.value = result.records; } catch (e) { if (current === scheduleGeneration) scheduleError.value = e.message; } finally { if (current === scheduleGeneration) schedulesLoading.value = false; } }
function selectDate(date) { selectedDate.value = date; loadSchedules(); }
async function book(schedule) { const target = `/pages/confirm/index?scheduleId=${schedule.id}&doctorId=${id}`; if (await ensureLogin(target)) uni.navigateTo({ url: target }); }
onLoad(options => { id = options.id; load(); initialized = true; });
onShow(() => { if (initialized && doctor.value) loadSchedules(); });
</script>
<style scoped>
.large { width: 130rpx; height: 130rpx; font-size: 55rpx; border-radius: 29rpx; }.doctor-name { font-size: 39rpx; font-weight: 600; }.intro-label { font-size: 26rpx; color: #537761; font-weight: 600; margin-bottom: 10rpx; }.date-scroll { white-space: nowrap; margin-top: 25rpx; }.dates { display: inline-flex; gap: 15rpx; }.date-item { width: 95rpx; border-radius: 18rpx; text-align: center; padding: 20rpx 0; background: #fff; border: 1rpx solid #e8eee5; }.selected { background: #12836d; border-color: #12836d; color: #fff; }.day-label { font-size: 22rpx; color: #7f9184; }.selected .day-label,.selected .day-month { color: #c7eddb; }.day-number { font-size: 37rpx; font-weight: 600; margin-top: 12rpx; }.day-month { font-size: 20rpx; color: #8b9c8e; margin-top: 9rpx; }.slot-card { display: flex; align-items: center; justify-content: space-between; margin-top: 22rpx; padding: 29rpx; }.slot-time { font-size: 33rpx; font-weight: 600; }.slot-count { margin-top: 12rpx; font-size: 24rpx; color: #58947c; }.full { color: #a4afa6; }
</style>
